const $=id=>document.getElementById(id);
const loginPage=$('loginPage'),appPage=$('appPage'),loginForm=$('loginForm'),btnSalir=$('btnSalir'),trabajoForm=$('trabajoForm'),btnAdmin=$('btnAdmin'),adminLoginPage=$('adminLoginPage'),adminLoginForm=$('adminLoginForm'),adminUsuario=$('adminUsuario'),adminPassword=$('adminPassword'),btnCancelarAdmin=$('btnCancelarAdmin'),adminPage=$('adminPage'),btnVolver=$('btnVolver'),adminForm=$('adminForm'),adminUnidad=$('adminUnidad'),adminSemana=$('adminSemana'),adminTexto=$('adminTexto'),adminContenidoLista=$('adminContenidoLista'),trabajosContainer=$('trabajosContainer'),unidadesContainer=$('unidadesContainer'),totalTrabajos=$('totalTrabajos'),emptyMessage=$('emptyMessage'),buscar=$('buscar'),filtroCategoria=$('filtroCategoria'),filtroUnidad=$('filtroUnidad'),filtroSemana=$('filtroSemana'),limpiarFiltros=$('limpiarFiltros'),btnVerTareas=$('btnVerTareas'),btnMiPerfil=$('btnMiPerfil');
const usuarioCorrecto='P01898G@upla.edu.pe',passwordCorrecto='joseespinal_2003',adminCorrecto='admin@campus.com',passwordAdminCorrecto='admin_2003';
let trabajos=JSON.parse(localStorage.getItem('trabajosCampusHTML'))||[{id:1,titulo:'Informe de Resistencia de Materiales',curso:'Ingeniería',categoria:'Informes',descripcion:'Trabajo final con cálculos, gráficos y conclusiones.',fecha:'2026-07-07',archivo:'informe-resistencia.pdf',autor:'JOSE LUIS ESPINAL HUAMAN',unidad:1,semana:2},{id:2,titulo:'Proyecto de página web personal',curso:'Programación',categoria:'Proyectos',descripcion:'Diseño inicial de un sitio web para portafolio universitario.',fecha:'2026-07-02',archivo:'proyecto-web.zip',autor:'JOSE LUIS ESPINAL HUAMAN',unidad:2,semana:1}];
let textosSemanas=JSON.parse(localStorage.getItem('textosSemanasCampus'))||{};
function guardarTrabajos(){localStorage.setItem('trabajosCampusHTML',JSON.stringify(trabajos))}
function semanaGlobal(u,s){return(Number(u)-1)*4+Number(s)}
function clave(u,s){return`unidad_${u}_semana_${s}`}
function textoSemana(u,s){return textosSemanas[clave(u,s)]||''}
function guardarTextos(){localStorage.setItem('textosSemanasCampus',JSON.stringify(textosSemanas))}
function mostrarApp(){loginPage.classList.add('hidden');adminLoginPage.classList.add('hidden');adminPage.classList.add('hidden');appPage.classList.remove('hidden');setTimeout(renderizarTodo,0)}
function mostrarLogin(){appPage.classList.add('hidden');adminLoginPage.classList.add('hidden');adminPage.classList.add('hidden');loginPage.classList.remove('hidden')}
loginForm.addEventListener('submit',e=>{e.preventDefault();let c=$('correo').value.trim(),p=$('password').value.trim();if(c===usuarioCorrecto&&p===passwordCorrecto){localStorage.setItem('usuarioCampusHTML',c);mostrarApp()}else alert('Correo o contraseña incorrectos. Inténtalo nuevamente.')});
btnSalir.onclick=()=>{localStorage.removeItem('usuarioCampusHTML');mostrarLogin()};btnAdmin.onclick=()=>{appPage.classList.add('hidden');adminLoginPage.classList.remove('hidden')};btnCancelarAdmin.onclick=()=>{adminLoginPage.classList.add('hidden');appPage.classList.remove('hidden')};btnVolver.onclick=()=>{adminPage.classList.add('hidden');appPage.classList.remove('hidden');renderizarTodo()};btnVerTareas.onclick=()=>document.querySelector('.works-section').scrollIntoView({behavior:'smooth'});btnMiPerfil.onclick=()=>document.querySelector('#perfilSection').scrollIntoView({behavior:'smooth'});
adminLoginForm.addEventListener('submit',e=>{e.preventDefault();if(adminUsuario.value.trim()===adminCorrecto&&adminPassword.value.trim()===passwordAdminCorrecto){adminLoginPage.classList.add('hidden');adminPage.classList.remove('hidden');adminUsuario.value='';adminPassword.value='';renderizarPanelAdmin()}else alert('Usuario o contraseña de admin incorrectos.')});
trabajoForm.addEventListener('submit',e=>{e.preventDefault();let a=$('archivo');trabajos.unshift({id:Date.now(),titulo:$('titulo').value,curso:$('curso').value,categoria:$('categoria').value,unidad:Number($('unidad').value),semana:Number($('semana').value),descripcion:$('descripcion').value||'Sin descripción.',autor:$('autor').value||'Estudiante',archivo:a.files.length?a.files[0].name:'Archivo no adjuntado',fecha:new Date().toISOString().slice(0,10)});guardarTrabajos();trabajoForm.reset();$('autor').value='JOSE LUIS ESPINAL HUAMAN';renderizarTodo();alert('Trabajo guardado correctamente.')});
adminForm.addEventListener('submit',e=>{e.preventDefault();let u=Number(adminUnidad.value),s=Number(adminSemana.value);textosSemanas[clave(u,s)]=adminTexto.value.trim();guardarTextos();renderizarPanelAdmin();renderizarUnidades();alert('Texto guardado correctamente.')});
function filtrados(){let tx=buscar.value.toLowerCase(),cat=filtroCategoria.value,u=filtroUnidad.value,s=filtroSemana.value;return trabajos.filter(t=>`${t.titulo} ${t.curso} ${t.descripcion} ${t.autor}`.toLowerCase().includes(tx)&&(cat==='Todos'||t.categoria===cat)&&(u==='Todas'||Number(t.unidad)===Number(u))&&(s==='Todas'||Number(t.semana)===Number(s)))}
function renderizarTrabajos(){let arr=filtrados();trabajosContainer.innerHTML='';if(!arr.length){emptyMessage.classList.remove('hidden');return}emptyMessage.classList.add('hidden');arr.forEach(t=>{let sg=semanaGlobal(t.unidad,t.semana),txt=textoSemana(t.unidad,t.semana);let card=document.createElement('article');card.className='work-card';card.innerHTML=`<div class="work-top"><div class="file-icon">📄</div><span class="category">${t.categoria}</span></div><h3>${t.titulo}</h3><p>📘 ${t.curso}</p><p>📚 Unidad ${t.unidad} - Semana ${sg}</p><p>👤 ${t.autor}</p><p>🗓️ ${t.fecha}</p>${txt?`<p class="week-content-card">📝 ${txt}</p>`:''}<p class="description">${t.descripcion}</p><div class="file-name">🏷️ ${t.archivo}</div><div class="work-actions"><button class="btn-light" onclick="verTrabajo('${t.archivo}')">Ver</button><button class="btn-danger" onclick="eliminarTrabajo(${t.id})">Eliminar</button></div>`;trabajosContainer.appendChild(card)})}
function renderizarUnidades(){unidadesContainer.innerHTML='';for(let u=1;u<=4;u++){let total=trabajos.filter(t=>Number(t.unidad)===u).length,html='';for(let s=1;s<=4;s++){let sg=semanaGlobal(u,s),cant=trabajos.filter(t=>Number(t.unidad)===u&&Number(t.semana)===s).length,txt=textoSemana(u,s),res=txt?txt.substring(0,45)+(txt.length>45?'...':''):'Sin texto';html+=`<button class="week-btn" onclick="filtrarPorSemana(${u},${s})"><span class="week-title">Semana ${sg}</span><strong>${cant}</strong><small>${res}</small></button>`}let div=document.createElement('div');div.className='unit-card';div.innerHTML=`<div class="unit-head"><h3>Unidad ${u}</h3><span>${total} trabajos</span></div><div class="weeks-grid">${html}</div>`;unidadesContainer.appendChild(div)}}
function renderizarPanelAdmin(){adminContenidoLista.innerHTML='';for(let u=1;u<=4;u++){let html='';for(let s=1;s<=4;s++){html+=`<div class="admin-week-item"><div><strong>Unidad ${u} - Semana ${semanaGlobal(u,s)}</strong><p>${textoSemana(u,s)||'Sin texto agregado todavía.'}</p></div><button class="btn-secondary btn-small" onclick="editarTextoSemana(${u},${s})">Editar</button></div>`}let div=document.createElement('div');div.className='admin-unit-block';div.innerHTML=`<h3>Unidad ${u}</h3>${html}`;adminContenidoLista.appendChild(div)}}
function editarTextoSemana(u,s){adminUnidad.value=String(u);adminSemana.value=String(s);adminTexto.value=textoSemana(u,s);adminTexto.focus()}
function renderizarTodo(){totalTrabajos.textContent=trabajos.length;renderizarUnidades();renderizarTrabajos()}
function eliminarTrabajo(id){trabajos=trabajos.filter(t=>t.id!==id);guardarTrabajos();renderizarTodo()}
function filtrarPorSemana(u,s){filtroUnidad.value=String(u);filtroSemana.value=String(s);renderizarTrabajos();document.querySelector('.works-section').scrollIntoView({behavior:'smooth'})}
function verTrabajo(n){alert('Archivo registrado: '+n+'\n\nEn HTML puro solo se guarda el nombre del archivo. Para guardar y descargar archivos reales se necesita backend o base de datos.')}
buscar.oninput=renderizarTrabajos;filtroCategoria.onchange=renderizarTrabajos;filtroUnidad.onchange=renderizarTrabajos;filtroSemana.onchange=renderizarTrabajos;limpiarFiltros.onclick=()=>{buscar.value='';filtroCategoria.value='Todos';filtroUnidad.value='Todas';filtroSemana.value='Todas';renderizarTrabajos()};
localStorage.getItem('usuarioCampusHTML')?mostrarApp():mostrarLogin();


// Refuerzo v6: si el navegador carga lento o hay caché, vuelve a pintar las unidades.
window.addEventListener('DOMContentLoaded', function () {
  if (typeof renderizarTodo === 'function' && !document.getElementById('appPage').classList.contains('hidden')) {
    renderizarTodo();
  }
});

window.addEventListener('load', function () {
  if (typeof renderizarTodo === 'function' && !document.getElementById('appPage').classList.contains('hidden')) {
    renderizarTodo();
  }
});
